language: cpp

os:
  - linux
  - osx

dist: trusty

compiler:
  - clang
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "YlZmQnVY0FCZ0jwXlHB/vqdfSFgHRyGWZej6oEC9YQyhXSiiz4C2zEVW6RuHQT6OPWsehDsjNFBBJyGsJIX8xp1Z5Y2n8YhVPsv6fLFiz0AF5WrJXhycC4Gz174CqPT6vSTZ42KmSrXqPE6fpH1mZNSFBwXrTmhwWcjLlbWvnmo="
  matrix:
    - QT=5  BREW=
    - QT=5  BREW=ex  PPA=ubuntu-sdk-team/ppa
    - QT=51 BREW=ex  PPA=beineri/opt-qt511-trusty
    - QT=52 BREW=ex  PPA=beineri/opt-qt521-trusty
    - QT=53 BREW=ex  PPA=beineri/opt-qt532-trusty
    - QT=54 BREW=ex  PPA=beineri/opt-qt542-trusty
    - QT=55 BREW=ex  PPA=beineri/opt-qt551-trusty
    - QT=56 BREW=ex  PPA=beineri/opt-qt562-trusty
    - QT=56 BREW=ex  PPA=beineri/opt-qt563-trusty
    - QT=57 BREW=ex  PPA=beineri/opt-qt571-trusty
    - QT=58 BREW=ex  PPA=beineri/opt-qt58-trusty
    - QT=59 BREW=ex  PPA=beineri/opt-qt591-trusty
    - QT=59 BREW=ex  PPA=beineri/opt-qt592-trusty
    - QT=59 BREW=ex  PPA=beineri/opt-qt593-trusty
    - QT=59 BREW=ex  PPA=beineri/opt-qt594-trusty
    - QT=59 BREW=ex  PPA=beineri/opt-qt595-trusty
    - QT=59 BREW=ex  PPA=beineri/opt-qt596-trusty
    - QT=510 BREW=ex PPA=beineri/opt-qt-5.10.1-trusty

matrix:
  # Qt no longer supports GCC on OSX.
  allow_failures:
    - { os: osx, compiler: gcc, env: QT=5  BREW= }
  exclude:
    - { os: osx, env: QT=5  BREW=ex  PPA=ubuntu-sdk-team/ppa      }
    - { os: osx, env: QT=51 BREW=ex  PPA=beineri/opt-qt511-trusty }
    - { os: osx, env: QT=52 BREW=ex  PPA=beineri/opt-qt521-trusty }
    - { os: osx, env: QT=53 BREW=ex  PPA=beineri/opt-qt532-trusty }
    - { os: osx, env: QT=54 BREW=ex  PPA=beineri/opt-qt542-trusty }
    - { os: osx, env: QT=55 BREW=ex  PPA=beineri/opt-qt551-trusty }
    - { os: osx, env: QT=56 BREW=ex  PPA=beineri/opt-qt562-trusty }
    - { os: osx, env: QT=56 BREW=ex  PPA=beineri/opt-qt563-trusty }
    - { os: osx, env: QT=57 BREW=ex  PPA=beineri/opt-qt571-trusty }
    - { os: osx, env: QT=58 BREW=ex  PPA=beineri/opt-qt58-trusty  }
    - { os: osx, env: QT=59 BREW=ex  PPA=beineri/opt-qt591-trusty }
    - { os: osx, env: QT=59 BREW=ex  PPA=beineri/opt-qt592-trusty }
    - { os: osx, env: QT=59 BREW=ex  PPA=beineri/opt-qt593-trusty }
    - { os: osx, env: QT=59 BREW=ex  PPA=beineri/opt-qt594-trusty }
    - { os: osx, env: QT=59 BREW=ex  PPA=beineri/opt-qt595-trusty }
    - { os: osx, env: QT=59 BREW=ex  PPA=beineri/opt-qt596-trusty }
    - { os: osx, env: QT=510 BREW=ex PPA=beineri/opt-qt-5.10.1-trusty }

addons:
  coverity_scan:
    project:
      name: "pcolby/aws-sdk-qt"
      description: "Build submitted via Travis CI"
    notification_email: git@colby.id.au
    build_command_prepend: >
      cp -a "$TRAVIS_BUILD_DIR" "$TRAVIS_BUILD_DIR-scan" &&
      pushd "$TRAVIS_BUILD_DIR-scan" &&
      qmake -qt=qt5 -Wall -Wlogic -Wparser CONFIG+=debug_and_release
    build_command: make all
    branch_pattern: coverity

before_install:
  - '[[ "$TRAVIS_OS_NAME" != linux || -z "$PPA" ]] || sudo add-apt-repository -y ppa:$PPA'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'
  - '[ "$TRAVIS_OS_NAME" != osx   ] || brew update'

install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install cppcheck doxygen graphviz lcov'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || sudo apt-get -qy install qt${QT}base qt${QT}xmlpatterns'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || sudo apt-get -qy install qtbase5-dev libqt5xmlpatterns5-dev'
  - '[ "$TRAVIS_OS_NAME" != linux ] || gem install lcoveralls'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install cppcheck doxygen graphviz qt$BREW'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt$BREW'

before_script:
  - cppcheck --error-exitcode=1 --quiet
    --suppress=syntaxError:test/unit/src/core/testawsabstractresponse.cpp
    code-generation/src src test
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || . /opt/qt$QT/bin/qt$QT-env.sh'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || export QT_SELECT=qt5'
  - mkdir -p "$TRAVIS_BUILD_DIR-build"
  - cmake -B"$TRAVIS_BUILD_DIR-build" -H"$TRAVIS_BUILD_DIR" && make -C"$TRAVIS_BUILD_DIR-build" -j2 codegen all

script:
  - make -C "$TRAVIS_BUILD_DIR-build" -j2 codegen all
  #- make -C "$TRAVIS_BUILD_DIR-build" -j2 check TESTARGS=-silent

after_success:
  # Generate LCOV coverage reports
  - make -C "$TRAVIS_BUILD_DIR-build/test/unit/all" coverage
  - sed -i -e "s|^SF:/home/travis/build/aws-sdk-qt|SF:$TRAVIS_BUILD_DIR|"
    "$TRAVIS_BUILD_DIR-build/release/unit-test-all-tmp/coverage.info"
  # Report code coverage to coveralls.io
  - lcoveralls --retry-count 5
    "$TRAVIS_BUILD_DIR-build/release/unit-test-all-tmp/coverage.info"
  # Report code coverage to codecov.io
  - curl https://codecov.io/bash > /tmp/codecov.sh
  - bash /tmp/codecov.sh -f "$TRAVIS_BUILD_DIR-build/release/unit-test-all-tmp/coverage.info"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fbd7a436c2f67325cffc
