language: cpp

dist: focal

compiler:
  - clang
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "YlZmQnVY0FCZ0jwXlHB/vqdfSFgHRyGWZej6oEC9YQyhXSiiz4C2zEVW6RuHQT6OPWsehDsjNFBBJyGsJIX8xp1Z5Y2n8YhVPsv6fLFiz0AF5WrJXhycC4Gz174CqPT6vSTZ42KmSrXqPE6fpH1mZNSFBwXrTmhwWcjLlbWvnmo="

matrix:
  include:
    - os: linux
      env: QT=5
      addons: { apt: { packages: [ qtbase5-dev, libqt5xmlpatterns5-dev ] } }
    - os: linux
      env: QT=512
      addons: { apt: { packages: [ qt512base, qt512xmlpatterns ], sources: [ sourceline: beineri/opt-qt-5.12.9-focal ] } }
    - os: linux
      env: QT=514
      addons: { apt: { packages: [ qt514base, qt514xmlpatterns ], sources: [ sourceline: beineri/opt-qt-5.14.2-focal ] } }
    - os: linux
      env: QT=515
      addons: { apt: { packages: [ qt515base, qt515xmlpatterns ], sources: [ sourceline: beineri/opt-qt-5.15.0-focal ] } }
    - os: osx

addons:
  apt: { packages: [ cppcheck, doxygen, graphviz, lcov, libgrantlee5-dev ] }
  homebrew: { packages: [ cppcheck, doxygen, graphviz, qt ], update: true }
  coverity_scan:
    project:
      name: "pcolby/aws-sdk-qt"
      description: "Build submitted via Travis CI"
    notification_email: git@colby.id.au
    build_command_prepend: >
      cp -a "$TRAVIS_BUILD_DIR" "$TRAVIS_BUILD_DIR-scan" &&
      pushd "$TRAVIS_BUILD_DIR-scan" &&
      qmake -qt=qt5 -Wall -Wlogic -Wparser CONFIG+=debug_and_release
    build_command: make all
    branch_pattern: coverity

before_install:

install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || gem install lcoveralls'
  #- '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt'

before_script:
  - cppcheck --error-exitcode=1 --quiet
    --suppress=syntaxError:test/unit/src/core/testawsabstractresponse.cpp
    code-generation/src src test
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || . /opt/qt$QT/bin/qt$QT-env.sh'
  #- '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || export QT_SELECT=qt5'
  - mkdir -p "$TRAVIS_BUILD_DIR-build"
  - cmake -B"$TRAVIS_BUILD_DIR-build" -H"$TRAVIS_BUILD_DIR"

script:
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || . /opt/qt$QT/bin/qt$QT-env.sh'
  - make -C "$TRAVIS_BUILD_DIR-build" -j2 codegen all
  #- make -C "$TRAVIS_BUILD_DIR-build" -j2 check TESTARGS=-silent

after_success:
  # Generate LCOV coverage reports
  - make -C "$TRAVIS_BUILD_DIR-build/test/unit/all" coverage
  - sed -i -e "s|^SF:/home/travis/build/aws-sdk-qt|SF:$TRAVIS_BUILD_DIR|"
    "$TRAVIS_BUILD_DIR-build/release/unit-test-all-tmp/coverage.info"
  # Report code coverage to coveralls.io
  - lcoveralls --retry-count 5
    "$TRAVIS_BUILD_DIR-build/release/unit-test-all-tmp/coverage.info"
  # Report code coverage to codecov.io
  - curl https://codecov.io/bash > /tmp/codecov.sh
  - bash /tmp/codecov.sh -f "$TRAVIS_BUILD_DIR-build/release/unit-test-all-tmp/coverage.info"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fbd7a436c2f67325cffc
