name: Build

on: [push]

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Grantlee
      run: sudo apt install libgrantlee5-dev
    - name: Build
      run: |
        cmake -S "$GITHUB_WORKSPACE"  -B "$RUNNER_TEMP"
        cmake --build "$RUNNER_TEMP" --target codegen

  linux-clang:
    runs-on: ubuntu-latest
    strategy: { matrix: { qt: [ '5.12.10', '5.15.0' ] } }
    steps:
    - uses: actions/checkout@v2
    - name: Install Tools
      run: sudo apt install clang libgrantlee5-dev
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
    - name: Build
      env: { CC: clang, CXX: clang++ }
      run: |
        cmake -S "$GITHUB_WORKSPACE"  -B "$RUNNER_TEMP"
        cmake --build "$RUNNER_TEMP" --target QtAwsAcm QtAwsCore QtAwsS3 QtAwsS3Control QtAwsXRay

  linux-gcc:
    runs-on: ubuntu-latest
    strategy: { matrix: { qt: [ '5.12.10', '5.15.0' ] } }
    steps:
    - uses: actions/checkout@v2
    - name: Install Tools
      run: sudo apt install gcc libgrantlee5-dev
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
    - name: Build
      env: { CC: gcc, CXX: g++ }
      run: |
        cmake -S "$GITHUB_WORKSPACE"  -B "$RUNNER_TEMP"
        cmake --build "$RUNNER_TEMP" --target QtAwsAcm QtAwsCore QtAwsS3 QtAwsS3Control QtAwsXRay

  macos-clang:
    runs-on: macOS-latest
    strategy: { matrix: { qt: [ '5.12.10', '5.15.0' ] } }
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
    - name: Build
      env: { CC: clang, CXX: clang++ }
      run: |
        cmake -S "$GITHUB_WORKSPACE"  -B "$RUNNER_TEMP"
        cmake --build "$RUNNER_TEMP" --target QtAwsAcm QtAwsCore QtAwsS3 QtAwsS3Control QtAwsXRay

  macos-gcc:
    runs-on: macOS-latest
    strategy: { matrix: { qt: [ '5.12.10', '5.15.0' ] } }
    steps:
    - uses: actions/checkout@v2
    - name: Install GCC
      run: brew install gcc
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
    - name: Build
      env: { CC: gcc, CXX: g++ }
      run: |
        cmake -S "$GITHUB_WORKSPACE"  -B "$RUNNER_TEMP"
        cmake --build "$RUNNER_TEMP" --target QtAwsAcm QtAwsCore QtAwsS3 QtAwsS3Control QtAwsXRay

  # @todo windows-mingw

  # @todo windows-msvc
