# SPDX-FileCopyrightText: 2013-2022 Paul Colby <git@colby.id.au>
# SPDX-License-Identifier: LGPL-3.0-or-later

name: Static Analysis

on: [push, pull_request]

jobs:
  CodeQL:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      run: sudo apt update && sudo apt upgrade && sudo apt install qtbase5-dev
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: cpp
    - name: Configure
      run: cmake -S "$GITHUB_WORKSPACE" -B "$RUNNER_TEMP"
    - name: Build A-I
      run: make $(make help | grep -v '_autogen$' | sed -Ene 's/^\.\.\. (QtAws[A-I])/\1/p')
      working-directory: ${{ runner.temp }}
    - name: Build J-Z
      run: make $(make help | grep -v '_autogen$' | sed -Ene 's/^\.\.\. (QtAws[J-Z])/\1/p')
      working-directory: ${{ runner.temp }}
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  Cppcheck:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Cppcheck
      run: sudo apt update && sudo apt upgrade && sudo apt install cppcheck
    - uses: actions/checkout@v3
    - name: Perform Cppcheck Analysis
      run: ./.cppcheck.sh --xml --xml-version=2 2> "$RUNNER_TEMP/cppcheck.xml"
    - name: Generate Report
      if: ${{ failure() }}
      run: |
        cppcheck-htmlreport --title='LibQtAws' --file="$RUNNER_TEMP/cppcheck.xml" \
          --report-dir="$RUNNER_TEMP/report" --source-dir="$GITHUB_WORKSPACE"
    - name: Upload Report
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: Cppcheck HTML Report
        path: "${{ runner.temp }}/report"
